# Generated by Django 5.1.7 on 2025-03-25 08:28

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="User's first name", max_length=100)),
                ('last_name', models.CharField(help_text="User's last name", max_length=100)),
                ('email', models.EmailField(help_text='Unique email address for the user', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text="User's contact phone number", max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('account_type', models.CharField(choices=[('developer', 'Developer'), ('maintenance', 'Maintenance'), ('technician', 'Technician'), ('admin', 'Administrator')], default='developer', help_text='Type of user account', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of user account creation')),
                ('last_login', models.DateTimeField(blank=True, help_text='Timestamp of last user login', null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can access the admin site')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account should be treated as active')),
                ('profile_picture', models.ImageField(blank=True, help_text='Optional profile picture for the user', null=True, upload_to='profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
