# Generated by Django 5.1.7 on 2025-03-25 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_data', models.JSONField(blank=True, help_text='Flexible additional profile data', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Profile creation timestamp')),
                ('skills', models.TextField(blank=True, help_text='Programming languages and technologies')),
                ('github_username', models.CharField(blank=True, help_text='GitHub username for professional portfolio', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_data', models.JSONField(blank=True, help_text='Flexible additional profile data', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Profile creation timestamp')),
                ('company_name', models.CharField(blank=True, help_text='Official name of the maintenance company', max_length=255)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration or license number', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_data', models.JSONField(blank=True, help_text='Flexible additional profile data', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Profile creation timestamp')),
                ('specialization', models.CharField(blank=True, help_text="Technician's area of expertise", max_length=100)),
                ('years_of_experience', models.IntegerField(blank=True, help_text='Years of professional experience', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
