# Generated by Django 5.1.7 on 2025-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_User', '0002_developerprofile_maintenanceprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerprofile',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Primary business or residential address', null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text="Developer's company name (if applicable)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='developer_name',
            field=models.CharField(default='Unknown Developer', help_text='Full name of the building developer', max_length=255),
        ),
    ]
