# Generated by Django 5.1.7 on 2025-03-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account_User', '0003_remove_developerprofile_github_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='years_of_experience',
        ),
    ]
