# Generated by Django 5.1.7 on 2025-03-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_User', '0004_remove_technicianprofile_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('developer', 'Developer'), ('maintenance', 'Maintenance'), ('technician', 'Technician'), ('admin', 'Administrator')], help_text='Type of user account', max_length=50),
        ),
    ]
