# Generated by Django 5.1.7 on 2025-03-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_User', '0005_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='developer_name',
            field=models.CharField(blank=True, help_text='Full name of the building developer', max_length=255, null=True),
        ),
    ]
